### PR TITLE
Fix dependency issues

### PR DESCRIPTION
**Pull request by Ruberto**
Hey Everyone, 

We are going to be using your API thought that we could easily just help you out getting your ruby wrapper up to date. 

This change may induce issues for legacy applications so I would suggest you create a new tag and we / anyone looking at using it in the future can just use an updated version 😄 

let me know if you would like to change something with this 👍

### CODE REVIEW

**Comment by chaselee** [comment]
thanks @Ruberto! I was actually just working on this, so your timing couldn't be better 👍 

I'll be doing a full review and checking to make sure everything works correctly, but would you mind making this 2.0.0? I know it's not really proper semver to do so assuming this doesn't introduce backwards-incompatible changes (it might, and I'm fine with that), but given the scope of the changes I think it's the right move to mitigate folks auto-updating to this version. 

Let me know if you have any other thoughts and thanks again!

**Comment by Ruberto** [comment]
Hey @chaselee, I have bumped the version for you. 

Yeah if they have just included the gem as `gem  'mbsy'` then they will most likely pull 2.0.0 if they bundle update. Unless there is a specific tag that they can add to the Gemfile to point to an older version. 

glad to be able to help.

**Comment by chaselee** [comment]
Thanks again @Ruberto!

**Comment by chaselee** [comment]
@Ruberto this is [available on RubyGems](https://rubygems.org/gems/mbsy/versions/2.0.0) now.

**Pull request merged**
